---
title: "SeqPlots R workflow"
author: "Przemyslaw Setmpor"
date: "`r format(Sys.Date(), '%d %B %Y')`"
package: "`r paste('SeqPlots', packageVersion('seqplots'))`"
abstract: >
  SeqPlots is a tool for plotting average track signals (e.g.
  read coverage) and sequence motif densities over user specified genomic
  features. The data can be visualized in linear plots with error
  estimates or as series of heatmaps that can be sorted and clustered. The
  software can be run locally on a desktop or deployed on a server and
  allows easy data sharing. SeqPlots pre-calculates and stores binary
  result matrices, allowing rapid plot generation. Plots can also be run
  in batch.
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
output: 
  BiocStyle::html_document:
    toc: true
---

```{r echo=FALSE, results='asis', echo=FALSE}
# knit the first three lines of first.Rmd
files <- c(
  'Files.md',
  'PlotSets.md',
  'Plotting.md',
  'Heatmaps.md',
  'Outputs.md',
  'Batch.md',
  'SaveAndLoad.md',
  'AdvOup.md',
  'Genomes.md',
  'Errors.md',
  'Terms.md',
  'References.md'
)

cat(knitr::knit_child(
    text = gsub(
        "img/",
        "../inst/seqplots/www/help/img/",
        unlist(lapply(file.path('../inst/seqplots/www/help', files), readLines))
    ),
    quiet = TRUE
), sep = '\n')
```

Session Information
===================
```{r echo=FALSE}
sessionInfo()
```







